### ISSUE TITLE
'$' is undefined (conflicts with expose-loader?)

### ISSUE THREAD

**Issue by rpokrovskij** [SebastianS90/webpack-polyfill-injector#16] opened 2018-05-06 21:37 UTC
Configuration that I have to provide two polifills actual for IE11 only:

```
module.exports = {
    entry: {
        app: `webpack-polyfill-injector?${JSON.stringify({
            modules: ['./src/index.es8.js'] 
        })}!` 
    },
    output: {
        path: outputFolderPath,
        filename: '[name].js'
    },
    plugins: [
        new PolyfillInjectorPlugin({
            polyfills: [
                'Element.prototype.closest',
                'Element.prototype.classList'
            ]
        }),
        new ManifestPlugin(),
        new CleanPlugin(outputFolderPath, { verbose: false }),
        extractCSS
    ],
    module: {
        rules: [



            {
                // MANAGE DEPENDENCY. METHOD 2. Manage dependencies at run-time. Adds modules to the global object
                // https://github.com/webpack-contrib/expose-loader
                // exposes $, jQuery, window.$, window.jQuery on global level;
                test: require.resolve('jquery'),
                use: [{
                    loader: 'expose-loader',
                    options: 'jQuery'
                }, {
                    loader: 'expose-loader',
                    options: '$'
                }]
            },

            {
                test: /\.(scss)$/,
                use:
                    extractCSS.extract({
                        fallback: 'style-loader',
                        use:
                            [
                                {
                                    loader: 'css-loader'   // translates CSS into CommonJS JavaScript modules
                                }, {
                                    loader: 'postcss-loader', // run post css actions (here autoprefixer)
                                    options: {
                                        sourceMap: true,
                                        plugins: function () {
                                            return [
                                                require('precss'),
                                                require('autoprefixer') // adds "vendor's" prefixes e.g. -webkit-input-placeholder , -ms-input-placeholder etc.
                                            ];
                                        }
                                    }
                                }, {
                                    loader: 'sass-loader', options: {
                                        sourceMap: true
                                    } // compiles Sass to CSS
                                }]
                    })

            },
            {
                test: /\.ts$/,
                "loader": 'awesome-typescript-loader'
            },
            {
                test: /\.(woff2|woff|ttf|svg|png)$/,
                use: 'url-loader'
            },
            {
                test: /\.(es8)\.(js)$/,
                include: /src/,
                exclude: /node_modules/,
                use: {
                    loader: "babel-loader",
                    options: {
                        babelrc: false,
                        presets: [
                            ["@babel/env",
                                {
                                    "targets": {
                                        "browsers": ["last 2 chrome versions", "ie 11", "safari 11", "edge 15", "firefox 59"]
                                    },
                                    "debug": true
                                }
                            ]
                        ]
                    }
                }
            },

            {
                include: /src/,
                exclude: /node_modules/,
                test: /global\.js$/,
                use: {
                    loader: "script-loader"
                }
            }
        ]
    }
};
```

Expected behaviour: node's 'closest' become available for IE11

Results: when with Chrome and Edge everithing is OK with IE 11 I see

![image](https://user-images.githubusercontent.com/11598038/39678044-e6e43e32-518d-11e8-8321-f001565f5c10.png)

There $ was used in HTML inline scripts.

I think the reason is that `expose-loader` was not started and $ was not assigned to global.

So the questions is could `expose-loader` and 'webpack-polyfill-injector' work together? Could you add it to the  documentation?

**Comment by SebastianS90** [comment] 2018-05-09 07:20
Thanks for the report. I have a few questions:

- Do I assume right that the problem goes away when you disable `webpack-polyfill-injector`? If not, then it's nothing I can help with, disregard the remaining questions.
- Does the browser you use have native support for both polyfills? If not, please try with current chrome or specify a polyfill that is supported natively, such that `webpack-polyfill-injector` does not need to load any polyfills. If the problem goes away, then it is likely caused by the loading part of `webpack-polyfill-injector`. Please let me know and then revert back to the configuration that triggers the error you reported.
- Please patch `node_modules/webpack-polyfill-injector/src/injector-multi.js` ([source](https://github.com/SebastianS90/webpack-polyfill-injector/blob/v2.0.2/src/injector-multi.js#L12-L14)) and `node_modules/webpack-polyfill-injector/src/injector-single.js` ([source](https://github.com/SebastianS90/webpack-polyfill-injector/blob/v2.0.2/src/injector-single.js#L9-L11)) as follows:
```diff
     js.onerror = function onError(message) {
-         console.error('Could not load the polyfills: ' + message);
+         console.log('Could not load the polyfills');
+         console.log(message);
     };
```
Check what the content of the `message` object is that was logged to the console.

**Comment by rpokrovskij** [comment] 2018-05-09 09:29
Thank you for your reply! 
1) yes, you are right, if I remove webpack-polyfill-injector - problem with $ disappear (on IE11, there are no such problem on Chrome and Edge)
2) Chrome and Edge supports `closed` and `classList`  functionaliy, plyfill targets only IE11
3) After patch I see that error is an node event

![image](https://user-images.githubusercontent.com/11598038/39806876-9f34417a-5383-11e8-8f2f-8afe6fe06604.png)

unfortunately I do not know how to dig in it

I see that some useful information can be extracted from bundle structure (precedence of loaders? ) but I can't evaluate it.

bundle:
[app.js.zip](https://github.com/SebastianS90/webpack-polyfill-injector/files/1987186/app.js.zip)

**Comment by SebastianS90** [comment] 2018-05-09 09:40
One more question: Is `app.js` in your html `<head>` or in `<body>`?

**Comment by rpokrovskij** [comment] 2018-05-09 10:08
It is in `body`, at the end of page (in ASP way of file loading optimizations: css in head, scripts at the end).
Is it wrong? Can't find any requirements on this.

I have tryed to put it into the `head` . The same error (with IE11). 

```
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="/dist/main.css?v=6izFi2f_2QgG2IBq7e3Jp2GDyGCykTNZ7XNU9LfItZw" />
        <script src="/dist/app.js?v=AtYuu-mqhjjoYUOH2bgfZKjBWFDyIrVWk1a3OR2jQ1M"></script>
</head>
```

Feel need to repeat: reports about "$ nof found" are also from page's `<script>$('select').dropdown()</scrpt`> **inline** code, not from code that is "bundled". That means `expose-loader` was not started and this can be its problem. I just can't understand it by meself and need your help.

**Comment by SebastianS90** [comment] 2018-05-09 11:52
Ok, then I probably know the reason for the problem: It is important to know that `expose-loader` assigns the global variables (e.g. `window.$`) as soon as it finds a `require()` call in your bundle. So everything strongly depends on the order.

### Loading order in different scenarios

Without `webpack-polyfill-injector`:
1. Your entry module (`./src/index.es8.js`) requires `./src/multiselect/DashboardCode.BsMultiSelect.es8.js`
2. `./src/multiselect/DashboardCode.BsMultiSelect.es8.js` requires `jquery`, it will now be exposed by `expose-loader`
3. The inline script using `$` is executed now (it appears after `app.js` in your html document)

With `webpack-polyfill-injector`, but no polyfills need to be loaded:
1. `webpack-polyfill-injector` is the new entry module. It is executed and sees that no polyfills need to be loaded. So it will directly execute your normal entry module, i.e. require `./src/index.es8.js`.
2. step 1-3 from above

With `webpack-polyfill-injector`, polyfills need to be loaded, and `app.js` loaded from the `body`:
1. `webpack-polyfill-injector` sees that it needs to load polyfills. A new `script` tag will be inserted to the document head.
2. Since the html page has already been loaded and body scripts have started to be executed, further script execution is not blocked. The inserted `script` tag will load asynchronously.
3. The inline script using `$` is executed and fails
4. Due to the script failure in step 3, the inserted `script` tag will abort. Another error is shown.

If you move `app.js` from `body` to `head`, the following should happen:
1. `webpack-polyfill-injector` sees that it needs to load polyfills. A new `script` tag will be inserted to the document head.
2. Since the browser is still processing`head` scripts, the `body` will not be processed as long as the new `script` tag is loading.
3. The new `script` tag finishes loading (polyfills are now available), and the `onload` function is triggered.
4. The `onload` function executes your normal entry module, i.e. `./src/index.es8.js`
5. From there, `./src/multiselect/DashboardCode.BsMultiSelect.es8.js` and thus also `jquery` will be loaded. `expose-loader` exposes `jquery` as `window.$`.
6. Head-Scripts are finished. Body scripts (including your inline script using `$`) are executed


### Possible solutions

#### `app.js` in head
Ensure that you load `app.js` from the head section and use exposed stuff only from inside the body section. Then it should work without problems.

#### Delay inline script
Another solution would be to put the inline script in a function, i.e.
```html
<body>
  <script>function executeMeWhenFinished() { /* do something with jquery */ }</script>
  <script src="app.js"></script>
</body>
```
and call `executeMeWhenFinished()` from within `./src/index.es8.js` (but only after requiring `./src/multiselect/DashboardCode.BsMultiSelect.es8.js`)

#### Use expose-loader outside of polyfill-injector:
This one is a bit tricky. Create a new entry module `entry.js` and define it as entry (without polyfill-injector). Inside `entry.js`, you have:
```js
import('jquery'); // will trigger expose-loader
import('webpack-polyfill-injector?{modules:["./index.es8.js"]}'); // will load polyfills (if necessary) and then start your normal entry module
```

**Comment by rpokrovskij** [comment] 2018-05-09 12:40
Just moving to head doesn't help (doublechecked). Trying next two.
P.S. Thank you for detailed explanations. I feel with your help I understand webpack better.

**Comment by SebastianS90** [comment] 2018-05-09 12:41
If that does not help either, please remove the inline script which uses `$` and check in developer console whether `window.$` is defined once the page load completes.

**Comment by rpokrovskij** [comment] 2018-05-09 13:37
If you are talking about solution "move to the head" then window.$ is not defined after document is loaded:

inline code:
```
    <script type="text/javascript">
        (function () {
            console.log("window and window.$ on script on load");
            console.log(window);
            console.log(window.$);
            //var select = $('.bootstrap-multiselect').dashboardCodeBsMultiSelect();
        })();

        document.addEventListener("DOMContentLoaded", function (event) {
            console.log("window and window.$ on script on DOM load");
            console.log(window);
            console.log(window.$);
        });
    </script>
}
```

result:

![image](https://user-images.githubusercontent.com/11598038/39817608-41f628ec-53a7-11e8-8c21-6b8460e2fb35.png)

**Comment by SebastianS90** [comment] 2018-05-09 13:42
Can you see something useful in the network tab? I'm wondering why the onerror function of the script tag is triggered... Maybe you can also find something useful in the logged event (the one under the `Could not load polyfills` line)

**Comment by rpokrovskij** [comment] 2018-05-09 13:52
bingo. network tab contains an error. polyfills.11.js is not in requested relative url, it is in dist folder `http://localhost:63557/dist/polyfills.11.js ` 

![image](https://user-images.githubusercontent.com/11598038/39818503-bd072f0c-53a9-11e8-8663-58d3a7312650.png)

Can't find how it can be confiugred? Is it a part of webpack-polyfill-injector configuration?

**Comment by SebastianS90** [comment] 2018-05-09 14:02
That's good, now we have something specific to look into.

Please try it with
```diff
     output: {
         path: outputFolderPath,
+        publicPath: '/',
         filename: '[name].js'
     },
```

This should also fix problems you'll get later when using dynamic chunk loading within your bundle, since that also relies on `publicPath` being set.

**Comment by rpokrovskij** [comment] 2018-05-09 17:45
After configuring publicPath: '/dist/', polyfills loaded without problem and first two methods works.

But I have difficulties with third method (which seems for me most attractive since it is a declarative and logical: load expose-loaders modules - means jquery - before polyfills because they doesn't use them).

I have created ./src/loaders.js with

```
import('jquery'); // will trigger expose-loader
import('webpack-polyfill-injector?{modules:["./index.es8.js"]}'); // will load polyfills (if necessary) and then start your normal entry module

```

And now webpack.config looks like:

```
module.exports = {
    entry: './src/loaders.js',
    output: {
        path: outputFolderPath,
        publicPath: '/dist/',
        filename: '[name].js'
        //filename: '[name].js'
        //filename: '[name].[chunkhash].js',
    },
    plugins: [
        new PolyfillInjectorPlugin({
            polyfills: [
                'Element.prototype.closest',
                'Element.prototype.classList'
            ]
        }),
   ...
```

building webpack I have an error **The plugin must be used together with the loader!**

```
pm : Error: [webpack-polyfill-injector] The plugin must be used together with the loader!
At line:1 char:1
+ npm run build
+ ~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error: [webpack...ith the loader!:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
    at compilation.hooks.additionalAssets.tapPromise 
(D:\cot\DashboardCode\Routines\AdminkaV1\Injected.AspCore.MvcApp\node_modules\webpack-polyfill-injector\src\plugin.js:28:27)
    at AsyncSeriesHook.eval [as callAsync] (eval at create 
(D:\cot\DashboardCode\Routines\AdminkaV1\Injected.AspCore.MvcApp\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:8:1)

```

That means when webpack initialize plugin it can't find the loader usage (because it's usage is delayed and moved to loaders.js). Are you sure that this is possible with current version? Or I did it wrong?

**Comment by SebastianS90** [comment] 2018-05-09 18:28
We are making progress, nice :smile:

Have you tried to delete/comment [the lines which generate the error](https://github.com/SebastianS90/webpack-polyfill-injector/blob/v2.0.2/src/plugin.js#L27-L29)? If that works then I'll remove the check. It's purpose was mainly to warn people who upgrade from version `0.x` to `1.x` and don't read the migration guide.

**Comment by rpokrovskij** [comment] 2018-05-09 22:08
Thank you for your patience.

Unfortunately this (comment check rule) provoke new `webpack` error: **Module not found: Error: Can't resolve 'fs' in 'D:\cot\DashboardCode\Routines\AdminkaV1\Injected.AspCore.MvcApp\node_modules\webpack-polyfill-injector\src'**

(this folder exists and it is local npm rep)

```
node interpretate webpack config:
process.env.npm_config_shell: C:\WINDOWS\system32\cmd.exe
process.env.npm_config_version: 
process.env.npm_config_script_shell: 
process.env.npm_package_version: 1.0.0
Hash: b1cbc5b35fcd41286f29
Version: webpack 4.7.0
Time: 8940ms
Built at: 2018-05-10 01:01:05
        Asset       Size  Chunks             Chunk Names
      main.js   8.09 KiB    main  [emitted]  main
         0.js    225 KiB       0  [emitted]  
         1.js   22.5 MiB       1  [emitted]  
         2.js    303 KiB       2  [emitted]  
     main.css    212 KiB    main  [emitted]  main
manifest.json  136 bytes          [emitted]  
Entrypoint main = main.js main.css
[./node_modules/webpack-polyfill-injector/src/PluginState.js] (webpack)-polyfill-injector/src/PluginState.js 2.81 KiB {} {1} [built]
[./node_modules/webpack-polyfill-injector/src/helpers.js] (webpack)-polyfill-injector/src/helpers.js 1.93 KiB {} {1} [built]
[./node_modules/webpack-polyfill-injector/src/plugin.js?{modules:["./src/index.es8.js"]}] (webpack)-polyfill-injector/src/plugin.js?{modules:["./src/index.es8.js"]} 7.3 KiB {} {1} [built]
[./node_modules/webpack-sources/lib/CachedSource.js] (webpack)-sources/lib/CachedSource.js 1.99 KiB {} {1} [built]
[./node_modules/webpack-sources/lib/ConcatSource.js] (webpack)-sources/lib/ConcatSource.js 2.13 KiB {} {1} [built]
[./node_modules/webpack-sources/lib/LineToLineMappedSource.js] (webpack)-sources/lib/LineToLineMappedSource.js 1.23 KiB {} {1} [built]
[./node_modules/webpack-sources/lib/OriginalSource.js] (webpack)-sources/lib/OriginalSource.js 2.01 KiB {} {1} [built]
[./node_modules/webpack-sources/lib/PrefixSource.js] (webpack)-sources/lib/PrefixSource.js 1.86 KiB {} {1} [built]
[./node_modules/webpack-sources/lib/RawSource.js] (webpack)-sources/lib/RawSource.js 691 bytes {} {1} [built]
[./node_modules/webpack-sources/lib/ReplaceSource.js] (webpack)-sources/lib/ReplaceSource.js 5.94 KiB {} {1} [built]
[./node_modules/webpack-sources/lib/Source.js] (webpack)-sources/lib/Source.js 714 bytes {} {1} [built]
[./node_modules/webpack-sources/lib/SourceMapSource.js] (webpack)-sources/lib/SourceMapSource.js 1.85 KiB {} {1} [built]
[./node_modules/webpack-sources/lib/index.js] (webpack)-sources/lib/index.js 581 bytes {} {1} [built]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 489 bytes {} {1} {2} [built]
[./src/loaders.js] 197 bytes {main} [built]
    + 2115 hidden modules

ERROR in (webpack)-polyfill-injector/src/helpers.js
Module not found: Error: Can't resolve 'fs' in 'D:\cot\DashboardCode\Routines\AdminkaV1\Injected.AspCore.MvcApp\node_modules\webpack-polyfill-injector\src'
 @ (webpack)-polyfill-injector/src/helpers.js 2:9-22
 @ (webpack)-polyfill-injector/src/PluginState.js
 @ (webpack)-polyfill-injector/src/plugin.js?{modules:["./src/index.es8.js"]}
 @ ./src/loaders.js
npm : npm ERR! code ELIFECYCLE
At line:1 char:1
+ npm run build
```

so entry point ./src/loaders.js found and problem is it in its 
`import('webpack-polyfill-injector?{modules:["./src/index.es8.js"]}');` line

This can be important:
1) if this line is commented - webpack succeed
2) if this line is changed to `import('webpack-polyfill-injector?{modules:[]}');` - error is the same. Can't resolve fn...

**Comment by SebastianS90** [comment] 2018-05-10 03:51
We forgot the exclamation mark that tells webpack that the thing is a loader:
```
import('webpack-polyfill-injector?{modules:["./src/index.es8.js"]}!');
                                                                  ↑ here
```

Does it work that way?

**Comment by rpokrovskij** [comment] 2018-05-10 09:36
Thank you.
After exclamation mark webpack  compilation succeed .
Unfortunately $ sign is still not defined on global (after ba)
It seem like `import('jquery')` line from loaders.js doesn't trigger expose-loader.

Also compiled that way there are new js files after compilation which origin and purpose that I do not know `0.js` , `1.js`, `2.js` (and bundle change its name from `app.js` to `main.js`):

![image](https://user-images.githubusercontent.com/11598038/39863184-9d813330-544e-11e8-9688-08d970db8309.png)

note: polyfill.js is not loaded (possibly because jquery error prevent is)

![image](https://user-images.githubusercontent.com/11598038/39861700-14d609d8-544a-11e8-851e-168b5c0303ea.png)

 I am trying to debug bundle step by step but it is quite broken since there are a lot of code inside eval.

**Comment by SebastianS90** [comment] 2018-05-10 09:42
How about this updated `loaders.js`
```js
import main from 'webpack-polyfill-injector?{modules:["./src/index.es8.js"]}!';
import jquery from 'jquery';
```

`import(...)` generates a split point, which is probably not what we want here (as it requires Promise to be available). `import ... from ...` is static.

**Comment by SebastianS90** [comment] 2018-05-10 09:52
Another idea that just came to my mind:

```js
    entry: {
        app: [
            'jquery',
            `webpack-polyfill-injector?${JSON.stringify({
                modules: ['./src/index.es8.js'] 
            })}!`
        ]
    },
```

**Comment by rpokrovskij** [comment] 2018-05-10 10:48
First method works (thank you) but it seems race conditions is started sometimes and inline code

```
  <script type="text/javascript">
        document.addEventListener("DOMContentLoaded", function (event) {
            (function () {
                var select = $('.bootstrap-multiselect').dashboardCodeBsMultiSelect();
            })();
        });
    </script>
```

**sometimes** throws those errors (in IE11 ,and only in it)

that means at this moment index.es8.js (and jquery plugins) where not loaded.

![image](https://user-images.githubusercontent.com/11598038/39866216-6266524e-5458-11e8-9223-30994fcde435.png)

polyfills are loaded and works fine (when there are no "race condition")

**Comment by SebastianS90** [comment] 2018-05-10 10:54
Does it help if you place the `import jquery from 'jquery'` above the other import?

**Comment by rpokrovskij** [comment] 2018-05-10 11:21
1)yes, it is above: 

```
import main from 'webpack-polyfill-injector?{modules:["./src/index.es8.js"]}!';
import jquery from 'jquery'; 
```
this set jquery to global, but sometimes "inline js code" starts sooner then finish of loading index.es8.js 
[main.zip](https://github.com/SebastianS90/webpack-polyfill-injector/files/1991421/main.zip)


2) here is the same situations: sometimes works if no race condition started.

```
entry: {
        app: [
            'jquery',
            `webpack-polyfill-injector?${JSON.stringify({
                modules: ['./src/index.es8.js'] 
            })}!`,

        ]
    },
```

**Comment by SebastianS90** [comment] 2018-05-10 11:24
Right now you have `jquery` below `index`. Can you move `jquery` above the other one?

**Comment by rpokrovskij** [comment] 2018-05-10 11:38
the same, sometimes works fine, sometimes '**Object doesn't support property or method 'tooltip'**'

import jquery from 'jquery'; 
import main from 'webpack-polyfill-injector?{modules:["./src/index.es8.js"]}!';


[polyfills.zip](https://github.com/SebastianS90/webpack-polyfill-injector/files/1991476/polyfills.zip)

**Comment by SebastianS90** [comment] 2018-05-10 12:04
Your compiled module `"./src/loaders.js"`:

```js
_webpack_require__.r(__webpack_exports__);
/* harmony import */ var jquery__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! jquery */ "./node_modules/jquery/dist/jquery.js-exposed");
/* harmony import */ var jquery__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(jquery__WEBPACK_IMPORTED_MODULE_0__);
/* harmony import */ var webpack_polyfill_injector_modules_src_index_es8_js___WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! webpack-polyfill-injector?{modules:["./src/index.es8.js"]} */ "./node_modules/webpack-polyfill-injector/src/loader.js?{modules:[\"./src/index.es8.js\"]}!./");
/* harmony import */ var webpack_polyfill_injector_modules_src_index_es8_js___WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(webpack_polyfill_injector_modules_src_index_es8_js___WEBPACK_IMPORTED_MODULE_1__);
```

Your compiled module `"./node_modules/jquery/dist/jquery.js-exposed"`:
```js
/* WEBPACK VAR INJECTION */(function(global) {module.exports = global["$"] = __webpack_require__(/*! -!./jquery.js */ "./node_modules/jquery/dist/jquery.js");
/* WEBPACK VAR INJECTION */}.call(this, __webpack_require__(/*! ./../../webpack/buildin/global.js */ "./node_modules/webpack/buildin/global.js")))
```

That looks good, it definitively exposes `$` before the polyfills and `index` are loaded. So you should be fine using `$` in inline scripts after the `main.js` script.

However, it looks like your bundle extends `jQuery` with the `DashboardCodeBsMultiSelect` function. This function is of course only available for inline scripts *after* it has been attached to the global `jQuery` object. When polyfills have to be loaded, then your main bundle will become asynchronous, i.e. a request to load the polyfills file is made and only after it is finished the computation can continue. In the meantime, other scripts will be executed, e.g. your inline code (using the not yet defined `DashboardCodeBsMultiSelect` function). This is the race condition you noticed.

The solution is to defer your inline scripts to a point after the complete bundle has loaded. At the end of `index.es8.js`, put `document.body.bundleIsReady();` In your inline scripts, *before* you include `main.js`, put:
```js
document.body.bundleIsReady = function() {
  var select = $('.bootstrap-multiselect').dashboardCodeBsMultiSelect();
}
```

The other option is of course to put `$('.bootstrap-multiselect').dashboardCodeBsMultiSelect();` directly into `index.es8.js`, but I guess you have a specific reason that you want in inline.

**Comment by rpokrovskij** [comment] 2018-05-10 16:56
For me solution could be just to add selected polyfills to bundle (not creating new files) and conditionaly initialize them if browser needs those features at the start. Your **great injector** has a runtime agent that is suitable for this but you are trying too make all things smarter and load only polyfills browser needs (by inserting `<script>` what makes adding polyfills asynchronous). This will always conflict with `inline code`.

Thank you very much for your work and explanations.

P.S. Why I am trying to use "external" polyfills?
DashboardCodeBsMultiSelect  is a jquery/bootstrap4 plugin and I plan to move it to separate npm package.  Really I search the way how to do not include static polyfills into package, but DECLARE dependency on them in documentation with providing "recommended" method. And webpack-polyfill-injector looks like very suitable for webpack users

May be you can add "the synchronous" load option (means including all selected polyfills to the bundle) to `webpack-polyfill-injector`?  Unfortunatly I have no information how popular is bootstrap4+jquery+webpack combination, but I see the sense in using it...  

There is of course https://www.npmjs.com/package/dynamic-polyfill but it is dynamic (what is bad for me)...

**Comment by SebastianS90** [comment] 2018-05-11 07:28
Polyfills and libraries are difficult. There are versions for the polyfills that don't pollute the global namespace (e.g. `core-js` used in library mode). This is great for libraries in node applications, but for browser bundles that is not the best solution. You might end up with several different versions of the same polyfill in your bundle, thus unnecessarily increasing your bundle size. That of course affects page load time.

The typical way to solve it is that, as you suggested, every library documents what features are required. The application developer can then decide whether he wants to include those features as polyfill, or if he does only target browsers that implement the feature natively (e.g. because other parts of the code do not work with older browsers anyways).

So the application developer needs to include polyfills. One way to do it is the just pull in `babel-polyfill` as described [here](https://babeljs.io/docs/usage/polyfill/#usage-in-node--browserify--webpack). The resulting bundle will ship many polyfills and apply them if required. This is an easy solution that just works, and it is synchronous. But it has a downside: Some polyfills are rather large. The `Promise` polyfill for example has 4.5KB in the minified version. If it is included in the bundle, everyone has to download it, even if it will not be applied. So you punish all users because of some users that have old browsers.

My solution is a bit different. The application developer specifies exactly what features are needed. The browser then checks which features are missing, and then loads only the required polyfills in a separate request. This is done by magically inserting the script tag. Users of modern browsers which don't need the polyfills do not need the separate request. And the initial bundle is still small, because it does not contain any polyfills (only the small tests to see what features are missing). Shipping the tests and using them in the browser avoids relying on the user agent string and a table of which browser version supports what features.

The separate request comes with one downside you experienced: It is asynchronous. The bundle cannot continue executing before the polyfills are loaded, because it probably expects the polyfills to be set up. So my injector puts whatever you defined as `modules` option into the `onload` function of the inserted script tag. But now we cannot rely on the order of scripts in your html page anymore. Before, with only synchronous code, there was a guarantee that your bundle finished executing before the next script tag in the body (containing your inline code) is executed. This does not hold anymore, because your bundle is asynchronous. In fact, for normal internet connections (instead of localhost), the browser has a lot of time waiting for the polyfills to be loaded. In this timespan, your inline script will probably be executed.

My recommendation is to avoid inline scripts as much as possible. Put everything you can into your bundle, because then webpack and my injector can ensure that the stuff is executed in the right order, even if polyfills need to be loaded. Furthermore, it is good for caching. If you need inline code, make sure that it is just some definition, e.g. an object that stores user data printed out by your server-side PHP script. Or a function that will then be called by your bundle code when it is safe to do so. But don't run any code that interacts with the bundle, because you cannot rely on it to be executed if it is asynchronous. For large applications you probably have [code splitting](https://webpack.js.org/guides/code-splitting/), thus making your bundle asynchronous anyways.

I guess I will extend the documentation to resolve points adressed in this issue:
- [ ] document that `publicPath` needs to be set
- [ ] explicitly state that the bundle becomes asynchronous and what it does mean for the order of scripts
- [ ] document how `webpack-polyfill-injector` can be used in `import .. from ...` or `require(...)` calls

Regarding the synchronous option, I think that there are easier solutions to achieve this. Either put the required polyfills in your entry module (e.g. `require('core-js/fn/array/find-index');`) or into your webpack configuration (`entry: { app: ['core-js/fn/array/find-index', './index.js']}`). The whole point of my injector package is to only load the polyfills if required, load them from your own server (instead of the `polyfill.io` service), to work even if `Promise` is not supported natively, and to not trust the user agent string.

**Comment by rpokrovskij** [comment] 2018-05-11 10:33
`babel-polyfill` is for javascript standard lybrary polyfills not for DOM Node polyfills.  

You solution is brilliant. 
But for me and other plugin developers would be a big advantage to have one "webpack polyfill platform", not two: "one for sync" other for "async".

Exactly for DOM polyfills - they are small and can be included to the bundle. You already have compromises like this: "one file" option. IMHO Some plugins can be included to the bundle, biggest should be external: this also could help your users to  manage file count (as they have such needs): (A-B)^2<A^2 

> My recommendation is to avoid inline scripts as much as possible

It is too strong recommendation.  To have code and markup in one file is just very convenient for bootsrap/jquery applications. And I understand why: remember JSX "markup throuhg code" - by the same reason.

Thank you. it was great discussion for me.

**Comment by SebastianS90** [comment] 2018-05-11 10:46
> `babel-polyfill` is for javascript standard lybrary polyfills not for DOM Node polyfills.

Oh, I didn't know that they have less polyfills than `polyfill.io`. That convinces me to implement the synchronous option.

I opened two new issues (#17, #18) to track the results from this longish discussion here. Thanks for your input and debugging, very much appreciated. It's always nice to improve this package :smile: 

If you have time, you can of course work on the feature and send a PR. Otherwise I'll do it as soon as I find time for it. I'm closing this issue here now, but feel free to answer to this or one of the new issues if you have good input.

**Closed as completed by SebastianS90** 2018-05-11 10:46 UTC

**Comment by rpokrovskij** [comment] 2018-05-11 11:03
I have very little of webpack knowledge so work with high experienced developer like you would motivate me. But how it can be organized I can't imagine. If you will make the"sceleton" which should be filled with actual code , and share your knowledge about tools and environment (last years I work only with visual studio) - I could try to write it.
