### ISSUE TITLE
webpack 4 promise

### ISSUE THREAD

**Issue by kyoukhana** [SebastianS90/webpack-polyfill-injector#20] opened 2018-06-28 13:27 UTC
I am trying to integrate the polyfill-injector.  But i am not sure how to do it in my webpack file.  I just want one output file desktop.js

## Webpack Configuration file
```
const HtmlWebPackPlugin = require("html-webpack-plugin");
const webpack = require('webpack');
const path = require('path');
const PolyfillInjectorPlugin = require('webpack-polyfill-injector');

module.exports = {
    entry: ['./src/index.js'],
  output: {
    path: path.resolve(__dirname, "public"), // string
    filename: "desktop.js"
  },

  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules\/(?!(dom7|ssr-window|swiper)\/).*/,
        use: {
          loader: "babel-loader?presets[]=es2015"
        }
      },
     

      {
        test: /\.(gif|png|jpe?g|svg|jpg)$/i,
        use: [
          {
            loader: 'file-loader',
            options: {
              context: 'src',
              name: '[path][name].[ext]',
              outputPath: '/'
            }  
          }
        ]
      },


      {
        test: /\.css$/,
        use: [ 'style-loader', 'css-loader' ]
      },

      

      {
        test: /\.html$/,
        use: [
          {
            loader: "html-loader",
            options: { minimize: true }
          }
        ]
      }
    ]
  },
  plugins: [
    new HtmlWebPackPlugin({
      template: "./src/index.html",
      filename: "./index.html"
    }),
    

    new webpack.ProvidePlugin({
        $: 'jquery',
        jQuery: 'jquery',
        'window.jQuery': 'jquery'
      })
  ]
};
```

**Comment by SebastianS90** [comment] 2018-06-28 16:40
The output will consist of more than one file: a file for your normal bundle (`desktop.js`), and a file that contains the polyfills. Therefore you need to configure a flexible output path (in addition to adding the loader):
```diff
 module.exports = {
-    entry: ['./src/index.js'],
+    entry: {
+        desktop: `webpack-polyfill-injector?${JSON.stringify({
+            modules: ['./src/index.js']
+        })}!`
+    },
   output: {
     path: path.resolve(__dirname, "public"), // string
-    filename: "desktop.js"
+    filename: "[name].js"
   },
```

Finally, add the plugin:
```diff
   plugins: [
+    new PolyfillInjectorPlugin({
+      polyfills: [
+        'Promise',
+        // any other polyfill you need
+      ]
+    })
     new HtmlWebPackPlugin({
```

That should do it for your use case.

If you want to have the polyfills in `desktop.js` instead of in a separate file that is loaded only when needed, then you need to wait for #18. Unfortunately, I do not have much time for this project at the moment.

**Comment by kyoukhana** [comment] 2018-06-28 16:53
Is it possible to manually copy the code from the output into the desktop.js file

**Comment by SebastianS90** [comment] 2018-06-28 16:55
I would not recommend manually modifying the output files. then it would be way easier to just copy the polyfills into your application code instead of using this plugin. But why do you want to have everything in one file instead of loading the polyfills from a separate file only if they are required?

**Comment by SebastianS90** [comment] 2018-12-28 19:19
Closing as duplicate of #18

**Closed as completed by SebastianS90** 2018-12-28 19:19 UTC
